version: '3.8'

services:
  task4-back-end:
    image: softy-pinko-back-end:task4
    build:
      context: ./back-end
      dockerfile: Dockerfile
    ports:
      - "5252:5252"

  task4-front-end:
    image: softy-pinko-front-end:task4
    build: 
      context: ./front-end
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
    depends_on:
      - task4-back-end
