version: '3.8'

services:
  task5-back-end:
    image: softy-pinko-back-end:task5
    build:
      context: ./back-end
      dockerfile: Dockerfile

  task5-front-end:
    image: softy-pinko-front-end:task5
    build: 
      context: ./front-end
      dockerfile: Dockerfile
    depends_on:
      - task5-back-end

  task5-proxy:
    image: softy-pinko-proxy:task5
    build:
      context: ./proxy
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - task5-back-end
      - task5-front-end
